# Task 1: Predict the % of an student based on number of study hours Using Supervised Learning

- ## By - Ashish Chaudhary

# Supervised learning

Supervised Learning is a method where the models are trained using labeled data , it needs supervision to train the modells


In [1]:
#Importing All major libraries 
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Load the dataset
dataFrame = pd.read_csv('Dataset.csv')

In [3]:
# Check the head of dataset 
dataFrame.head()

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

In [4]:
# Checking info
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Hours   25 non-null     float64
 1   Scores  25 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 528.0 bytes


In [5]:
# Checking the distribution of the dataset 
dataFrame.plot(x='Hours',y='Scores',style='o')
plt.title('Hours vs Percentage')
plt.xlabel('The Hours Studied')
plt.ylabel('The percentage Score')

Text(0, 0.5, 'The percentage Score')

In [6]:
# Now we have to divide Our data set into Dependent and Independent Variables.X is feature or its independent variable here its hours
# It will not depend on the result and y is dependent variable for this variable we have to done prediction on this. so score is dependent variable 

X = dataFrame.iloc[:,:-1].values
y = dataFrame.iloc[:,1].values
# X = dataFrame.iloc[:,0].values.reshape(-1,1)
# y = dataFrame.iloc[:,1].values.reshape(-1,1)

In [7]:
# Now we have to split the dataset into training and testing so we will use skcit learn library 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
print(y_train)
print('\n')
print(y_test)

[35 24 86 76 17 47 85 42 81 88 67 30 25 60 30 75 21 54 95 41]


[20 27 69 30 62]


## **Linear Regression with Python Scikit Learn**
In this section we will see how the Python Scikit-Learn library for machine learning can be used to implement regression functions. We will start with simple linear regression involving two variables.

### **Simple Linear Regression**
In this regression task we will predict the percentage of marks that a student is expected to score based upon the number of hours they studied. This is a simple linear regression task as it involves just two variables.

In [9]:
# Now Feature scaling is not required in linear regression so 
# Now I have fit the training data in Linear Regression Algorithm
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)


LinearRegression()

In [10]:
# Now I will create a predictor so it can predict
y_predictor = regressor.predict(X_test)


In [11]:
# This is a dummy dataset 
y_predictor 

array([16.88414476, 33.73226078, 75.357018  , 26.79480124, 60.49103328])

In [12]:
# Now i Regression line will plot for training dataset 
plt.scatter(X_train,y_train)
plt.plot(X_train,regressor.predict(X_train))
plt.title('Hours vs score')

Text(0.5, 1.0, 'Hours vs score')

In [13]:
# Now i will regression line plot for testing dataset 
plt.scatter(X_test,y_test)
plt.plot(X_train,regressor.predict(X_train))
plt.title('Hours vs score - Test')

Text(0.5, 1.0, 'Hours vs score - Test')

In [14]:
# Now i will predict the scores from my model 
print(X_test)
y_predictor = regressor.predict(X_test)

[[1.5]
 [3.2]
 [7.4]
 [2.5]
 [5.9]]


In [15]:
# Now compare actual vs predicted model 
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_predictor})  
df  

Actual  Predicted
0      20  16.884145
1      27  33.732261
2      69  75.357018
3      30  26.794801
4      62  60.491033

In [22]:
# You can also test with your own data
raw_input = input('enter hours')
k = eval(raw_input)
hours = [[k]]
if hours == [[k]]:
    own_pred = regressor.predict(hours)
    print("No of Hours = {}".format(hours))
    print("Predicted Score = {}".format(own_pred[0]))

enter hours9.25
No of Hours = [[9.25]]
Predicted Score = 93.69173248737539


# **Evaluating the model**

The final step is to evaluate the performance of algorithm. This step is particularly important to compare how well different algorithms perform on a particular dataset. For simplicity here, we have chosen the mean square error. There are many such metrics.



we can't calculate accuracy for a regression model.
For regression, one of the matrices we've to get the score (ambiguously termed as accuracy) is R-squared (R2).

In [18]:
from sklearn import metrics  
print('Mean Absolute Error:',metrics.mean_absolute_error(y_test, y_predictor)) 
print('R squared value:',metrics.explained_variance_score(y_test, y_predictor)) 

Mean Absolute Error: 4.183859899002982
R squared value: 0.9482829156738145
